/* Generated by Yosys 0.19+36 (git sha1 a207fd4b335, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module iiitb_bc(Clk, reset, UpOrDown, Count);
  wire [3:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  input Clk;
  wire Clk;
  output [3:0] Count;
  wire [3:0] Count;
  input UpOrDown;
  wire UpOrDown;
  input reset;
  wire reset;
  sky130_fd_sc_hd__clkinv_1 _08_ (
    .A(Count[0]),
    .Y(_00_[0])
  );
  sky130_fd_sc_hd__clkinv_1 _09_ (
    .A(reset),
    .Y(_01_)
  );
  sky130_fd_sc_hd__and3_1 _10_ (
    .A(Count[0]),
    .B(Count[1]),
    .C(UpOrDown),
    .X(_02_)
  );
  sky130_fd_sc_hd__nor3_1 _11_ (
    .A(Count[0]),
    .B(Count[1]),
    .C(UpOrDown),
    .Y(_03_)
  );
  sky130_fd_sc_hd__maj3_1 _12_ (
    .A(Count[0]),
    .B(Count[1]),
    .C(UpOrDown),
    .X(_04_)
  );
  sky130_fd_sc_hd__nor2_1 _13_ (
    .A(_03_),
    .B(_04_),
    .Y(_05_)
  );
  sky130_fd_sc_hd__nor2_1 _14_ (
    .A(_02_),
    .B(_05_),
    .Y(_00_[1])
  );
  sky130_fd_sc_hd__nor2_1 _15_ (
    .A(_02_),
    .B(_03_),
    .Y(_06_)
  );
  sky130_fd_sc_hd__xnor2_1 _16_ (
    .A(Count[2]),
    .B(_06_),
    .Y(_00_[2])
  );
  sky130_fd_sc_hd__mux2i_1 _17_ (
    .A0(_03_),
    .A1(_02_),
    .S(Count[2]),
    .Y(_07_)
  );
  sky130_fd_sc_hd__xnor2_1 _18_ (
    .A(Count[3]),
    .B(_07_),
    .Y(_00_[3])
  );
  sky130_fd_sc_hd__dfrtp_1 _19_ (
    .CLK(Clk),
    .D(_00_[0]),
    .Q(Count[0]),
    .RESET_B(_01_)
  );
  sky130_fd_sc_hd__dfrtp_1 _20_ (
    .CLK(Clk),
    .D(_00_[1]),
    .Q(Count[1]),
    .RESET_B(_01_)
  );
  sky130_fd_sc_hd__dfrtp_1 _21_ (
    .CLK(Clk),
    .D(_00_[2]),
    .Q(Count[2]),
    .RESET_B(_01_)
  );
  sky130_fd_sc_hd__dfrtp_1 _22_ (
    .CLK(Clk),
    .D(_00_[3]),
    .Q(Count[3]),
    .RESET_B(_01_)
  );
endmodule
